sudo: required
services:
    - docker

before_install:
    - docker build -t sandeepkiranjs22/docker-react -f Dockerfile.dev .

script:
    - docker run sandeepkiranjs22/docker-react npm run test -- --coverage
    
